Kryonite Labs website MVP
kryonitelabs/docs pull request #1
Opened 2021-09-15 11:36 UTC by lusu007

## Proposed Changes

- add docusaurus template
- add some first customizations
- add github actions
- add pr and issue templates
- add dependabot

2021-09-16 19:31 UTC, lusu007 commented
Currently waiting for a logo. 😄

2021-09-16 19:32 UTC, lusu007 commented
Currently blocked by https://github.com/kryonitelabs/docs/pull/1

2021-09-18 15:22 UTC, ItsKev requested changes

2021-09-18 15:22 UTC, ItsKev commented on .github/workflows/documentation.yml
> +    if: github.event_name != 'push'
Wouldn't it be better to create two workflows here? There isn't really a benefit doing the two checks in one workflow right?

2021-09-18 15:22 UTC, ItsKev commented on .github/workflows/documentation.yml
> +          git config --global user.email "lukas.jost+kryonitelabs@outlook.com"
Shouldn't this use the bots email?

2021-09-18 15:22 UTC, ItsKev commented on README.md
> +$ GIT_USER=<Your GitHub username> USE_SSH=true yarn deploy
Is this a multi or single line command?

2021-09-18 15:22 UTC, ItsKev commented on blog/2021-09-16-what-is-kryonite-labs.md
> +The main project of [Kryonite Labs](https://github.com/kryonitelabs/) is our [Kryocloud](./docs/kryocloud/concept). Actually, we wanted to remove the word "cloud" from the name, as this software is n
```suggestion
The main project of [Kryonite Labs](https://github.com/kryonitelabs/) is [Kryocloud](./docs/kryocloud/concept). We didn't want to include the word "cloud" in the project's name, as this software is not a cloud, but an orchestrator. However, the name "cloud" for that kind of software has become widespread in the scene... 🤷‍♂️
```

2021-09-18 16:42 UTC, lusu007 commented on .github/workflows/documentation.yml
> +          git config --global user.email "lukas.jost+kryonitelabs@outlook.com"
Yeah... It's surely an artifact of the time when we didn't have a bot account yet 🤣

2021-09-18 16:43 UTC, lusu007 commented on .github/workflows/documentation.yml
> +    if: github.event_name != 'push'
Good point. I will change it.

2021-09-18 16:45 UTC, lusu007 commented on README.md
> +$ GIT_USER=<Your GitHub username> USE_SSH=true yarn deploy
The complete README.md file is generated by Docusaurus itself. I think the question is wether we change the README.md at all @ItsKev?

2021-09-19 15:49 UTC, ItsKev approved these changes

2021-09-19 15:49 UTC, merged